---
- name: apt-get install python3
  become: true
  apt:
    update_cache: yes
    state: present
    pkg:
    - pigpio
    - python-pigpio
    - python3-pigpio

- name: configure pigpiod 
  become: true
  shell: "systemctl enable pigpiod"

- name: start pigpiod 
  become: true
  shell: "systemctl start pigpiod"